### PR TITLE
Updated config.yml

### LINKED ISSUE #4: Welcome bot has broken link to celebration image
**Description**
See the screenshot and this comment as an example of the issue - https://github.com/layer5io/meshery-adapter-library/pull/2#issuecomment-705114834

An issue lie somewhere between this config - https://github.com/layer5io/advanced-istio-service-mesh-workshop/blob/master/.github/config.yml#L20 and the location of the image in the `.github/welcome` folder

**Expected Behavior**
See this as an example of what should happen - https://github.com/layer5io/layer5/pull/691#issuecomment-683525292

**Screenshots**
Screen Shot 2020-10-07 at 1 25 38 PM

### PR DESCRIPTION
**Pull request by agarwalamn**
Added the raw location of the image

**Description**

This PR fixes #4 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Comment by agarwalamn** [comment]
I just added the raw image location which should solve the issue

**Review by leecalcote — APPROVED** [review]
Beautiful. Much appreciated, @agarwalamn 👍

**Comment by agarwalamn** [comment]
Hey @leecalcote Thanks, can you mark it as `hacktoberfest-accepted` PR that would be great😃

**Comment by leecalcote** [comment]
@agarwalamn you betcha. Adding now....

**Pull request merged**
