### PR TITLE
Updated the Readme file

### LINKED ISSUE #20: [README] Need to add `Community Forum`
**Description**

<a href="https://github.com/layer5io/advanced-istio-service-mesh-workshop/blob/master/README.md">README.md</a> is the first file one should read when starting a new project. Our community launched `Discussion forum` for help seekers; needs to publish it officially on README.md for convenience.

### Screenshots

**Current Behaviour:**
image

**Desired Behaviour:**
Need to add a point below "Watch", by copy-paste below line:
```
- Discuss in the [Community Forum](https://discuss.layer5.io).
```
Give preview as below:
- Discuss in the [Community Forum](https://discuss.layer5.io).

**Environment:**
 - OS: any [e.g. Ubuntu]
 - Browser: any [e.g. Chrome, Safari]
 - Version: any [e.g. 22]
 - Device: any [e.g. laptop, iPhone 8]

### PR DESCRIPTION
**Pull request by Paras0-7**
**Description**

Added the Community Forum to the readme.
This PR fixes #20 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

### CODE REVIEW

**Review by includestdlibrary — CHANGES_REQUESTED** [review]
@Paras0-7 
1.  fork the repo and clone it  on your local pc  by `git clone ssh` (if you have generated your ssh key for your local system) or `git clone https`
2.  create new branch using `git checkout -b branch-name` and then edit the readme file, then stage your changes using `git add .`  and then commit using  `git commit --signedoff -m "Commit Message"`  
3. Add remote origin if you haven't using `git remote add origin SSH or HTTPS`
4. Push using `git push your branch name`
5. I hope you have configured global name and email so that you can sign off ! 

Hope this helps you! Try this!

ensure that your commits are signed off and if you want to check before push you can use `git log`

**Comment by amino19** [comment]
@Paras0-7 : You need to just signed-off your commits!
Don't directly commit to master, make your own branch by command: `git checkout -b <branch-name>`

- How to signed-off?
A. Click <a href="https://github.com/layer5io/advanced-istio-service-mesh-workshop/pull/21/checks?check_run_id=2924245199">here</a>

For more info., Join our <a href="https://slack.layer5.io/">Slack</a> :slightly_smiling_face:

**Comment by leecalcote** [comment]
Hang in there, @Paras0-7. You’ll get this. Be sure to ask any questions that you might have. @amino19 and @includestdlibrary are here to help.

**Comment by amino19** [comment]
@navendu-pottekkat  : There's no activity since few months back from contributor, need to _sign-off commits_ made. Will close after your review?
Will assign someone else for sure, to take this up! :slightly_smiling_face:

**Comment by leecalcote** [comment]
A valiant effort by @amino19 and @shuklaritvik06.

**Comment by shuklaritvik06** [comment]
> @navendu-pottekkat : There's no activity since few months back from contributor, need to _sign-off commits_ made. Will close after your review?
> Will assign someone else for sure, to take this up! slightly_smiling_face

I have done the changes please inform me if I should create a PR :)

**Comment by amino19** [comment]
> > @navendu-pottekkat : There's no activity since few months back from contributor, need to _sign-off commits_ made. Will close after your review?
> > Will assign someone else for sure, to take this up! slightly_smiling_face
> 
> I have done the changes please inform me if I should create a PR :)

@shuklaritivik06: Same here! Pl go ahead! : )

**Comment by warunicorn19** [comment]
Closing this one then.

**Comment by shuklaritvik06** [comment]
> > > @navendu-pottekkat : There's no activity since few months back from contributor, need to _sign-off commits_ made. Will close after your review?
> > > Will assign someone else for sure, to take this up! slightly_smiling_face
> > 
> > 
> > I have done the changes please inform me if I should create a PR :)
> 
> @shuklaritvik06: Same here! Pl go ahead! : )

Done :)

**Pull request closed without merging**
